# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "fc6bd5d381b4f7942a570801339fa6b5"
name = "Windy-app"
handle = "windy-app-1"
application_url = "https://puppy-highways-birmingham-relative.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://puppy-highways-birmingham-relative.trycloudflare.com/auth/callback",
  "https://puppy-highways-birmingham-relative.trycloudflare.com/auth/shopify/callback",
  "https://puppy-highways-birmingham-relative.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
